# Automatically generated file. DO NOT MODIFY
#
# This file is generated by device/razer/cheryl/setup-makefiles.sh

AB_OTA_PARTITIONS += \
    abl \
    bluetooth \
    cmnlib \
    cmnlib64 \
    devcfg \
    dsp \
    hyp \
    keymaster \
    mdtp \
    mdtpsecapp \
    modem \
    nvdef \
    rpm \
    tz \
    xbl
