#
# Automatically generated file. DO NOT MODIFY
#

PRODUCT_SOONG_NAMESPACES += \
    vendor/razer/cheryl

PRODUCT_COPY_FILES += \
    vendor/razer/cheryl/proprietary/system_ext/etc/dpm/dpm.conf:$(TARGET_COPY_OUT_SYSTEM_EXT)/etc/dpm/dpm.conf \
    vendor/razer/cheryl/proprietary/system_ext/etc/init/dpmd.rc:$(TARGET_COPY_OUT_SYSTEM_EXT)/etc/init/dpmd.rc \
    vendor/razer/cheryl/proprietary/system_ext/etc/permissions/com.qti.dpmframework.xml:$(TARGET_COPY_OUT_SYSTEM_EXT)/etc/permissions/com.qti.dpmframework.xml \
    vendor/razer/cheryl/proprietary/system_ext/etc/permissions/dpmapi.xml:$(TARGET_COPY_OUT_SYSTEM_EXT)/etc/permissions/dpmapi.xml \
    vendor/razer/cheryl/proprietary/system_ext/etc/permissions/qcrilhook.xml:$(TARGET_COPY_OUT_SYSTEM_EXT)/etc/permissions/qcrilhook.xml \
    vendor/razer/cheryl/proprietary/system_ext/etc/permissions/qti_libpermissions.xml:$(TARGET_COPY_OUT_SYSTEM_EXT)/etc/permissions/qti_libpermissions.xml \
    vendor/razer/cheryl/proprietary/system_ext/etc/permissions/qti_permissions.xml:$(TARGET_COPY_OUT_SYSTEM_EXT)/etc/permissions/qti_permissions.xml \
    vendor/razer/cheryl/proprietary/vendor/etc/acdbdata/RCL/Bluetooth_cal.acdb:$(TARGET_COPY_OUT_VENDOR)/etc/acdbdata/RCL/Bluetooth_cal.acdb \
    vendor/razer/cheryl/proprietary/vendor/etc/acdbdata/RCL/General_cal.acdb:$(TARGET_COPY_OUT_VENDOR)/etc/acdbdata/RCL/General_cal.acdb \
    vendor/razer/cheryl/proprietary/vendor/etc/acdbdata/RCL/Global_cal.acdb:$(TARGET_COPY_OUT_VENDOR)/etc/acdbdata/RCL/Global_cal.acdb \
    vendor/razer/cheryl/proprietary/vendor/etc/acdbdata/RCL/Handset_cal.acdb:$(TARGET_COPY_OUT_VENDOR)/etc/acdbdata/RCL/Handset_cal.acdb \
    vendor/razer/cheryl/proprietary/vendor/etc/acdbdata/RCL/Hdmi_cal.acdb:$(TARGET_COPY_OUT_VENDOR)/etc/acdbdata/RCL/Hdmi_cal.acdb \
    vendor/razer/cheryl/proprietary/vendor/etc/acdbdata/RCL/Headset_cal.acdb:$(TARGET_COPY_OUT_VENDOR)/etc/acdbdata/RCL/Headset_cal.acdb \
    vendor/razer/cheryl/proprietary/vendor/etc/acdbdata/RCL/Speaker_cal.acdb:$(TARGET_COPY_OUT_VENDOR)/etc/acdbdata/RCL/Speaker_cal.acdb \
    vendor/razer/cheryl/proprietary/vendor/etc/acdbdata/RCL/workspaceFile.qwsp:$(TARGET_COPY_OUT_VENDOR)/etc/acdbdata/RCL/workspaceFile.qwsp \
    vendor/razer/cheryl/proprietary/vendor/etc/audio/silence_48k.wav:$(TARGET_COPY_OUT_VENDOR)/etc/audio/silence_48k.wav \
    vendor/razer/cheryl/proprietary/vendor/etc/audio_tuning_mixer.txt:$(TARGET_COPY_OUT_VENDOR)/etc/audio_tuning_mixer.txt \
    vendor/razer/cheryl/proprietary/vendor/etc/camera/camera_config.xml:$(TARGET_COPY_OUT_VENDOR)/etc/camera/camera_config.xml \
    vendor/razer/cheryl/proprietary/vendor/etc/camera/s5k2l7sa05_rcl_wide_chromatix.xml:$(TARGET_COPY_OUT_VENDOR)/etc/camera/s5k2l7sa05_rcl_wide_chromatix.xml \
    vendor/razer/cheryl/proprietary/vendor/etc/camera/s5k3h7_rcl_front_chromatix.xml:$(TARGET_COPY_OUT_VENDOR)/etc/camera/s5k3h7_rcl_front_chromatix.xml \
    vendor/razer/cheryl/proprietary/vendor/etc/camera/s5k3m3sm_rcl_tele_chromatix.xml:$(TARGET_COPY_OUT_VENDOR)/etc/camera/s5k3m3sm_rcl_tele_chromatix.xml \
    vendor/razer/cheryl/proprietary/vendor/etc/cne/mwqem.conf:$(TARGET_COPY_OUT_VENDOR)/etc/cne/mwqem.conf \
    vendor/razer/cheryl/proprietary/vendor/etc/cne/profileMwqem.xml:$(TARGET_COPY_OUT_VENDOR)/etc/cne/profileMwqem.xml \
    vendor/razer/cheryl/proprietary/vendor/etc/cne/wqeclient/ATT/ATT_profile1.xml:$(TARGET_COPY_OUT_VENDOR)/etc/cne/wqeclient/ATT/ATT_profile1.xml \
    vendor/razer/cheryl/proprietary/vendor/etc/cne/wqeclient/ATT/ATT_profile2.xml:$(TARGET_COPY_OUT_VENDOR)/etc/cne/wqeclient/ATT/ATT_profile2.xml \
    vendor/razer/cheryl/proprietary/vendor/etc/cne/wqeclient/ATT/ATT_profile3.xml:$(TARGET_COPY_OUT_VENDOR)/etc/cne/wqeclient/ATT/ATT_profile3.xml \
    vendor/razer/cheryl/proprietary/vendor/etc/cne/wqeclient/ATT/ATT_profile4.xml:$(TARGET_COPY_OUT_VENDOR)/etc/cne/wqeclient/ATT/ATT_profile4.xml \
    vendor/razer/cheryl/proprietary/vendor/etc/cne/wqeclient/ATT/ATT_profile5.xml:$(TARGET_COPY_OUT_VENDOR)/etc/cne/wqeclient/ATT/ATT_profile5.xml \
    vendor/razer/cheryl/proprietary/vendor/etc/cne/wqeclient/ATT/ATT_profile6.xml:$(TARGET_COPY_OUT_VENDOR)/etc/cne/wqeclient/ATT/ATT_profile6.xml \
    vendor/razer/cheryl/proprietary/vendor/etc/cne/wqeclient/ROW/ROW_profile1.xml:$(TARGET_COPY_OUT_VENDOR)/etc/cne/wqeclient/ROW/ROW_profile1.xml \
    vendor/razer/cheryl/proprietary/vendor/etc/cne/wqeclient/ROW/ROW_profile15.xml:$(TARGET_COPY_OUT_VENDOR)/etc/cne/wqeclient/ROW/ROW_profile15.xml \
    vendor/razer/cheryl/proprietary/vendor/etc/cne/wqeclient/ROW/ROW_profile16.xml:$(TARGET_COPY_OUT_VENDOR)/etc/cne/wqeclient/ROW/ROW_profile16.xml \
    vendor/razer/cheryl/proprietary/vendor/etc/cne/wqeclient/ROW/ROW_profile17.xml:$(TARGET_COPY_OUT_VENDOR)/etc/cne/wqeclient/ROW/ROW_profile17.xml \
    vendor/razer/cheryl/proprietary/vendor/etc/cne/wqeclient/ROW/ROW_profile18.xml:$(TARGET_COPY_OUT_VENDOR)/etc/cne/wqeclient/ROW/ROW_profile18.xml \
    vendor/razer/cheryl/proprietary/vendor/etc/cne/wqeclient/ROW/ROW_profile19.xml:$(TARGET_COPY_OUT_VENDOR)/etc/cne/wqeclient/ROW/ROW_profile19.xml \
    vendor/razer/cheryl/proprietary/vendor/etc/cne/wqeclient/ROW/ROW_profile2.xml:$(TARGET_COPY_OUT_VENDOR)/etc/cne/wqeclient/ROW/ROW_profile2.xml \
    vendor/razer/cheryl/proprietary/vendor/etc/cne/wqeclient/ROW/ROW_profile20.xml:$(TARGET_COPY_OUT_VENDOR)/etc/cne/wqeclient/ROW/ROW_profile20.xml \
    vendor/razer/cheryl/proprietary/vendor/etc/cne/wqeclient/ROW/ROW_profile21.xml:$(TARGET_COPY_OUT_VENDOR)/etc/cne/wqeclient/ROW/ROW_profile21.xml \
    vendor/razer/cheryl/proprietary/vendor/etc/cne/wqeclient/ROW/ROW_profile3.xml:$(TARGET_COPY_OUT_VENDOR)/etc/cne/wqeclient/ROW/ROW_profile3.xml \
    vendor/razer/cheryl/proprietary/vendor/etc/cne/wqeclient/ROW/ROW_profile32.xml:$(TARGET_COPY_OUT_VENDOR)/etc/cne/wqeclient/ROW/ROW_profile32.xml \
    vendor/razer/cheryl/proprietary/vendor/etc/cne/wqeclient/ROW/ROW_profile4.xml:$(TARGET_COPY_OUT_VENDOR)/etc/cne/wqeclient/ROW/ROW_profile4.xml \
    vendor/razer/cheryl/proprietary/vendor/etc/cne/wqeclient/ROW/ROW_profile5.xml:$(TARGET_COPY_OUT_VENDOR)/etc/cne/wqeclient/ROW/ROW_profile5.xml \
    vendor/razer/cheryl/proprietary/vendor/etc/cne/wqeclient/ROW/ROW_profile6.xml:$(TARGET_COPY_OUT_VENDOR)/etc/cne/wqeclient/ROW/ROW_profile6.xml \
    vendor/razer/cheryl/proprietary/vendor/etc/cne/wqeclient/ROW/ROW_profile7.xml:$(TARGET_COPY_OUT_VENDOR)/etc/cne/wqeclient/ROW/ROW_profile7.xml \
    vendor/razer/cheryl/proprietary/vendor/etc/cne/wqeclient/VZW/VZW_profile1.xml:$(TARGET_COPY_OUT_VENDOR)/etc/cne/wqeclient/VZW/VZW_profile1.xml \
    vendor/razer/cheryl/proprietary/vendor/etc/cne/wqeclient/VZW/VZW_profile2.xml:$(TARGET_COPY_OUT_VENDOR)/etc/cne/wqeclient/VZW/VZW_profile2.xml \
    vendor/razer/cheryl/proprietary/vendor/etc/cne/wqeclient/VZW/VZW_profile3.xml:$(TARGET_COPY_OUT_VENDOR)/etc/cne/wqeclient/VZW/VZW_profile3.xml \
    vendor/razer/cheryl/proprietary/vendor/etc/cne/wqeclient/VZW/VZW_profile4.xml:$(TARGET_COPY_OUT_VENDOR)/etc/cne/wqeclient/VZW/VZW_profile4.xml \
    vendor/razer/cheryl/proprietary/vendor/etc/cne/wqeclient/VZW/VZW_profile5.xml:$(TARGET_COPY_OUT_VENDOR)/etc/cne/wqeclient/VZW/VZW_profile5.xml \
    vendor/razer/cheryl/proprietary/vendor/etc/cne/wqeclient/VZW/VZW_profile6.xml:$(TARGET_COPY_OUT_VENDOR)/etc/cne/wqeclient/VZW/VZW_profile6.xml \
    vendor/razer/cheryl/proprietary/vendor/etc/cp/FusionRectifyParams.bin:$(TARGET_COPY_OUT_VENDOR)/etc/cp/FusionRectifyParams.bin \
    vendor/razer/cheryl/proprietary/vendor/etc/cp/systemParams_autoGen_X3_Razer_Bokeh_12x3_O12_V8.0.09.bin:$(TARGET_COPY_OUT_VENDOR)/etc/cp/systemParams_autoGen_X3_Razer_Bokeh_12x3_O12_V8.0.09.bin \
    vendor/razer/cheryl/proprietary/vendor/etc/cp/systemParams_autoGen_X3_Razer_Fusion_12.2x12.2_O12.2_3_4AR_V8.0.9_fuserParams.bin:$(TARGET_COPY_OUT_VENDOR)/etc/cp/systemParams_autoGen_X3_Razer_Fusion_12.2x12.2_O12.2_3_4AR_V8.0.9_fuserParams.bin \
    vendor/razer/cheryl/proprietary/vendor/etc/cp/systemParams_autoGen_X3_Razer_Fusion_4.1x4.1_O4.1_9_16AR_V8.0.9_fuserParams.bin:$(TARGET_COPY_OUT_VENDOR)/etc/cp/systemParams_autoGen_X3_Razer_Fusion_4.1x4.1_O4.1_9_16AR_V8.0.9_fuserParams.bin \
    vendor/razer/cheryl/proprietary/vendor/etc/cp/systemParams_autoGen_X3_Razer_Fusion_7.7x7.7_O7.7_3_4AR_V8.0.9_fuserParams.bin:$(TARGET_COPY_OUT_VENDOR)/etc/cp/systemParams_autoGen_X3_Razer_Fusion_7.7x7.7_O7.7_3_4AR_V8.0.9_fuserParams.bin \
    vendor/razer/cheryl/proprietary/vendor/etc/cp/systemParams_autoGen_X3_Razer_Fusion_8.3x8.3_O8.3_9_16AR_V8.0.9_fuserParams.bin:$(TARGET_COPY_OUT_VENDOR)/etc/cp/systemParams_autoGen_X3_Razer_Fusion_8.3x8.3_O8.3_9_16AR_V8.0.9_fuserParams.bin \
    vendor/razer/cheryl/proprietary/vendor/etc/data/dsi_config.xml:$(TARGET_COPY_OUT_VENDOR)/etc/data/dsi_config.xml \
    vendor/razer/cheryl/proprietary/vendor/etc/data/netmgr_config.xml:$(TARGET_COPY_OUT_VENDOR)/etc/data/netmgr_config.xml \
    vendor/razer/cheryl/proprietary/vendor/etc/hdr_tm_config.xml:$(TARGET_COPY_OUT_VENDOR)/etc/hdr_tm_config.xml \
    vendor/razer/cheryl/proprietary/vendor/etc/init/android.hardware.bluetooth@1.0-service-qti.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/android.hardware.bluetooth@1.0-service-qti.rc \
    vendor/razer/cheryl/proprietary/vendor/etc/init/android.hardware.drm@1.1-service.widevine.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/android.hardware.drm@1.1-service.widevine.rc \
    vendor/razer/cheryl/proprietary/vendor/etc/init/cnd.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/cnd.rc \
    vendor/razer/cheryl/proprietary/vendor/etc/init/dataadpl.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/dataadpl.rc \
    vendor/razer/cheryl/proprietary/vendor/etc/init/dataqti.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/dataqti.rc \
    vendor/razer/cheryl/proprietary/vendor/etc/init/dpmQmiMgr.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/dpmQmiMgr.rc \
    vendor/razer/cheryl/proprietary/vendor/etc/init/ims_rtp_daemon_legacy.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/ims_rtp_daemon_legacy.rc \
    vendor/razer/cheryl/proprietary/vendor/etc/init/imsdatadaemon.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/imsdatadaemon.rc \
    vendor/razer/cheryl/proprietary/vendor/etc/init/imsqmidaemon.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/imsqmidaemon.rc \
    vendor/razer/cheryl/proprietary/vendor/etc/init/imsrcsd.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/imsrcsd.rc \
    vendor/razer/cheryl/proprietary/vendor/etc/init/netmgrd.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/netmgrd.rc \
    vendor/razer/cheryl/proprietary/vendor/etc/init/qcrild.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/qcrild.rc \
    vendor/razer/cheryl/proprietary/vendor/etc/init/vendor.qti.hardware.alarm@1.0-service.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/vendor.qti.hardware.alarm@1.0-service.rc \
    vendor/razer/cheryl/proprietary/vendor/etc/init/vendor.qti.hardware.perf@1.0-service.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/vendor.qti.hardware.perf@1.0-service.rc \
    vendor/razer/cheryl/proprietary/vendor/etc/init/vendor.qti.rmt_storage.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/vendor.qti.rmt_storage.rc \
    vendor/razer/cheryl/proprietary/vendor/etc/init/vendor.qti.tftp.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/vendor.qti.tftp.rc \
    vendor/razer/cheryl/proprietary/vendor/etc/perf/commonresourceconfigs.xml:$(TARGET_COPY_OUT_VENDOR)/etc/perf/commonresourceconfigs.xml \
    vendor/razer/cheryl/proprietary/vendor/etc/perf/perf-profile0.conf:$(TARGET_COPY_OUT_VENDOR)/etc/perf/perf-profile0.conf \
    vendor/razer/cheryl/proprietary/vendor/etc/perf/perf-profile1.conf:$(TARGET_COPY_OUT_VENDOR)/etc/perf/perf-profile1.conf \
    vendor/razer/cheryl/proprietary/vendor/etc/perf/perf-profile2.conf:$(TARGET_COPY_OUT_VENDOR)/etc/perf/perf-profile2.conf \
    vendor/razer/cheryl/proprietary/vendor/etc/perf/perf-profile3.conf:$(TARGET_COPY_OUT_VENDOR)/etc/perf/perf-profile3.conf \
    vendor/razer/cheryl/proprietary/vendor/etc/perf/perf-profile4.conf:$(TARGET_COPY_OUT_VENDOR)/etc/perf/perf-profile4.conf \
    vendor/razer/cheryl/proprietary/vendor/etc/perf/perf-profile5.conf:$(TARGET_COPY_OUT_VENDOR)/etc/perf/perf-profile5.conf \
    vendor/razer/cheryl/proprietary/vendor/etc/perf/perf-profile6.conf:$(TARGET_COPY_OUT_VENDOR)/etc/perf/perf-profile6.conf \
    vendor/razer/cheryl/proprietary/vendor/etc/perf/perfboostsconfig.xml:$(TARGET_COPY_OUT_VENDOR)/etc/perf/perfboostsconfig.xml \
    vendor/razer/cheryl/proprietary/vendor/etc/perf/targetconfig.xml:$(TARGET_COPY_OUT_VENDOR)/etc/perf/targetconfig.xml \
    vendor/razer/cheryl/proprietary/vendor/etc/perf/targetresourceconfigs.xml:$(TARGET_COPY_OUT_VENDOR)/etc/perf/targetresourceconfigs.xml \
    vendor/razer/cheryl/proprietary/vendor/etc/powerhint.xml:$(TARGET_COPY_OUT_VENDOR)/etc/powerhint.xml \
    vendor/razer/cheryl/proprietary/vendor/etc/qdcm_calib_data_NT36830_dual_dsi_cmd_mode_panel_with_DSC.xml:$(TARGET_COPY_OUT_VENDOR)/etc/qdcm_calib_data_NT36830_dual_dsi_cmd_mode_panel_with_DSC.xml \
    vendor/razer/cheryl/proprietary/vendor/etc/qdcm_calib_data_NT36830_dual_dsi_video_mode_panel_with_DSC.xml:$(TARGET_COPY_OUT_VENDOR)/etc/qdcm_calib_data_NT36830_dual_dsi_video_mode_panel_with_DSC.xml \
    vendor/razer/cheryl/proprietary/vendor/etc/seccomp_policy/imsrtp.policy:$(TARGET_COPY_OUT_VENDOR)/etc/seccomp_policy/imsrtp.policy \
    vendor/razer/cheryl/proprietary/vendor/etc/sensors/hals.conf:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/hals.conf \
    vendor/razer/cheryl/proprietary/vendor/etc/sensors/sensor_def_qcomdev.conf:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/sensor_def_qcomdev.conf \
    vendor/razer/cheryl/proprietary/vendor/etc/thermal-engine-cobalt.conf:$(TARGET_COPY_OUT_VENDOR)/etc/thermal-engine-cobalt.conf \
    vendor/razer/cheryl/proprietary/vendor/etc/thermal-engine.conf:$(TARGET_COPY_OUT_VENDOR)/etc/thermal-engine.conf \
    vendor/razer/cheryl/proprietary/vendor/firmware/RCL.img:$(TARGET_COPY_OUT_VENDOR)/firmware/RCL.img \
    vendor/razer/cheryl/proprietary/vendor/firmware/a530_pfp.fw:$(TARGET_COPY_OUT_VENDOR)/firmware/a530_pfp.fw \
    vendor/razer/cheryl/proprietary/vendor/firmware/a530_pm4.fw:$(TARGET_COPY_OUT_VENDOR)/firmware/a530_pm4.fw \
    vendor/razer/cheryl/proprietary/vendor/firmware/a540_gpmu.fw2:$(TARGET_COPY_OUT_VENDOR)/firmware/a540_gpmu.fw2 \
    vendor/razer/cheryl/proprietary/vendor/firmware/a540_zap.b00:$(TARGET_COPY_OUT_VENDOR)/firmware/a540_zap.b00 \
    vendor/razer/cheryl/proprietary/vendor/firmware/a540_zap.b01:$(TARGET_COPY_OUT_VENDOR)/firmware/a540_zap.b01 \
    vendor/razer/cheryl/proprietary/vendor/firmware/a540_zap.b02:$(TARGET_COPY_OUT_VENDOR)/firmware/a540_zap.b02 \
    vendor/razer/cheryl/proprietary/vendor/firmware/a540_zap.elf:$(TARGET_COPY_OUT_VENDOR)/firmware/a540_zap.elf \
    vendor/razer/cheryl/proprietary/vendor/firmware/a540_zap.mdt:$(TARGET_COPY_OUT_VENDOR)/firmware/a540_zap.mdt \
    vendor/razer/cheryl/proprietary/vendor/firmware/cpp_firmware_v1_12_0.fw:$(TARGET_COPY_OUT_VENDOR)/firmware/cpp_firmware_v1_12_0.fw \
    vendor/razer/cheryl/proprietary/vendor/firmware/fpctzappfingerprint.b00:$(TARGET_COPY_OUT_VENDOR)/firmware/fpctzappfingerprint.b00 \
    vendor/razer/cheryl/proprietary/vendor/firmware/fpctzappfingerprint.b01:$(TARGET_COPY_OUT_VENDOR)/firmware/fpctzappfingerprint.b01 \
    vendor/razer/cheryl/proprietary/vendor/firmware/fpctzappfingerprint.b02:$(TARGET_COPY_OUT_VENDOR)/firmware/fpctzappfingerprint.b02 \
    vendor/razer/cheryl/proprietary/vendor/firmware/fpctzappfingerprint.b03:$(TARGET_COPY_OUT_VENDOR)/firmware/fpctzappfingerprint.b03 \
    vendor/razer/cheryl/proprietary/vendor/firmware/fpctzappfingerprint.b04:$(TARGET_COPY_OUT_VENDOR)/firmware/fpctzappfingerprint.b04 \
    vendor/razer/cheryl/proprietary/vendor/firmware/fpctzappfingerprint.b05:$(TARGET_COPY_OUT_VENDOR)/firmware/fpctzappfingerprint.b05 \
    vendor/razer/cheryl/proprietary/vendor/firmware/fpctzappfingerprint.b06:$(TARGET_COPY_OUT_VENDOR)/firmware/fpctzappfingerprint.b06 \
    vendor/razer/cheryl/proprietary/vendor/firmware/fpctzappfingerprint.b07:$(TARGET_COPY_OUT_VENDOR)/firmware/fpctzappfingerprint.b07 \
    vendor/razer/cheryl/proprietary/vendor/firmware/fpctzappfingerprint.mbn:$(TARGET_COPY_OUT_VENDOR)/firmware/fpctzappfingerprint.mbn \
    vendor/razer/cheryl/proprietary/vendor/firmware/fpctzappfingerprint.mdt:$(TARGET_COPY_OUT_VENDOR)/firmware/fpctzappfingerprint.mdt \
    vendor/razer/cheryl/proprietary/vendor/firmware/ipa_fws.b00:$(TARGET_COPY_OUT_VENDOR)/firmware/ipa_fws.b00 \
    vendor/razer/cheryl/proprietary/vendor/firmware/ipa_fws.b01:$(TARGET_COPY_OUT_VENDOR)/firmware/ipa_fws.b01 \
    vendor/razer/cheryl/proprietary/vendor/firmware/ipa_fws.b02:$(TARGET_COPY_OUT_VENDOR)/firmware/ipa_fws.b02 \
    vendor/razer/cheryl/proprietary/vendor/firmware/ipa_fws.b03:$(TARGET_COPY_OUT_VENDOR)/firmware/ipa_fws.b03 \
    vendor/razer/cheryl/proprietary/vendor/firmware/ipa_fws.b04:$(TARGET_COPY_OUT_VENDOR)/firmware/ipa_fws.b04 \
    vendor/razer/cheryl/proprietary/vendor/firmware/ipa_fws.elf:$(TARGET_COPY_OUT_VENDOR)/firmware/ipa_fws.elf \
    vendor/razer/cheryl/proprietary/vendor/firmware/ipa_fws.mdt:$(TARGET_COPY_OUT_VENDOR)/firmware/ipa_fws.mdt \
    vendor/razer/cheryl/proprietary/vendor/firmware/tfa98xx.cnt:$(TARGET_COPY_OUT_VENDOR)/firmware/tfa98xx.cnt \
    vendor/razer/cheryl/proprietary/vendor/radio/qcril_database/qcril.db:$(TARGET_COPY_OUT_VENDOR)/radio/qcril_database/qcril.db \
    vendor/razer/cheryl/proprietary/vendor/radio/qcril_database/upgrade/0_initial.sql:$(TARGET_COPY_OUT_VENDOR)/radio/qcril_database/upgrade/0_initial.sql \
    vendor/razer/cheryl/proprietary/vendor/radio/qcril_database/upgrade/10_version_update_ecc_table.sql:$(TARGET_COPY_OUT_VENDOR)/radio/qcril_database/upgrade/10_version_update_ecc_table.sql \
    vendor/razer/cheryl/proprietary/vendor/radio/qcril_database/upgrade/1_version_intro.sql:$(TARGET_COPY_OUT_VENDOR)/radio/qcril_database/upgrade/1_version_intro.sql \
    vendor/razer/cheryl/proprietary/vendor/radio/qcril_database/upgrade/2_version_add_wps_config.sql:$(TARGET_COPY_OUT_VENDOR)/radio/qcril_database/upgrade/2_version_add_wps_config.sql \
    vendor/razer/cheryl/proprietary/vendor/radio/qcril_database/upgrade/3_version_update_wps_config.sql:$(TARGET_COPY_OUT_VENDOR)/radio/qcril_database/upgrade/3_version_update_wps_config.sql \
    vendor/razer/cheryl/proprietary/vendor/radio/qcril_database/upgrade/4_version_update_ecc_table.sql:$(TARGET_COPY_OUT_VENDOR)/radio/qcril_database/upgrade/4_version_update_ecc_table.sql \
    vendor/razer/cheryl/proprietary/vendor/radio/qcril_database/upgrade/5_version_update_ecc_table.sql:$(TARGET_COPY_OUT_VENDOR)/radio/qcril_database/upgrade/5_version_update_ecc_table.sql \
    vendor/razer/cheryl/proprietary/vendor/radio/qcril_database/upgrade/6_version_update_ecc_table.sql:$(TARGET_COPY_OUT_VENDOR)/radio/qcril_database/upgrade/6_version_update_ecc_table.sql \
    vendor/razer/cheryl/proprietary/vendor/radio/qcril_database/upgrade/7_version_update_ecc_table.sql:$(TARGET_COPY_OUT_VENDOR)/radio/qcril_database/upgrade/7_version_update_ecc_table.sql \
    vendor/razer/cheryl/proprietary/vendor/radio/qcril_database/upgrade/8_version_update_ecc_table.sql:$(TARGET_COPY_OUT_VENDOR)/radio/qcril_database/upgrade/8_version_update_ecc_table.sql \
    vendor/razer/cheryl/proprietary/vendor/radio/qcril_database/upgrade/9_version_update_ecc_table.sql:$(TARGET_COPY_OUT_VENDOR)/radio/qcril_database/upgrade/9_version_update_ecc_table.sql

PRODUCT_PACKAGES += \
    eglSubDriverAndroid \
    libEGL_adreno \
    libGLESv1_CM_adreno \
    libGLESv2_adreno \
    libQTapGLES \
    libq3dtools_adreno \
    libq3dtools_esx \
    hwcomposer.msm8998 \
    libC2D2 \
    libCB \
    libOpenCL \
    libadreno_utils \
    libadsprpc \
    libc2d30_bltlib \
    libdiag \
    libdsutils \
    libgpustats \
    libgsl \
    libhdr_tm \
    libidl \
    libllvm-glnext \
    libllvm-qcom \
    libmdmdetect \
    libperfgluelayer \
    libqdi \
    libqdp \
    libqmi \
    libqmi_cci \
    libqmi_client_helper \
    libqmi_client_qmux \
    libqmi_common_so \
    libqmi_csi \
    libqmi_encdec \
    libqmiservices \
    libqseed3 \
    libqti-perfd-client \
    libqti-perfd \
    libqti-util \
    libsdm-color \
    libsdm-diag \
    libsdm-disp-vndapis \
    libsdmcore \
    libsdmextension \
    libsdmutils \
    libsdsprpc \
    libsensor1 \
    libsensor_reg \
    libsns_low_lat_stream_stub \
    libthermalclient \
    libtinyxml2_1 \
    sensors.ssc \
    camera.msm8998 \
    sound_trigger.primary.msm8998 \
    libOmxVpp \
    libacdb-fts \
    libacdbloader \
    libacdbrtac \
    libactuator_ak7371_rcl_tele \
    libactuator_ak7371_rcl_wide \
    libadiertac \
    libadm \
    libaudcal \
    libc++_shared \
    libchromatix_s5k2l7sa05_rcl_wide_4k_preview_3a \
    libchromatix_s5k2l7sa05_rcl_wide_4k_video_3a \
    libchromatix_s5k2l7sa05_rcl_wide_720p_preview_3a \
    libchromatix_s5k2l7sa05_rcl_wide_720p_video_3a \
    libchromatix_s5k2l7sa05_rcl_wide_common \
    libchromatix_s5k2l7sa05_rcl_wide_cpp_hfr_120 \
    libchromatix_s5k2l7sa05_rcl_wide_cpp_hfr_120_hdr \
    libchromatix_s5k2l7sa05_rcl_wide_cpp_hfr_240 \
    libchromatix_s5k2l7sa05_rcl_wide_cpp_hfr_240_hdr \
    libchromatix_s5k2l7sa05_rcl_wide_cpp_hfr_60 \
    libchromatix_s5k2l7sa05_rcl_wide_cpp_hfr_60_hdr \
    libchromatix_s5k2l7sa05_rcl_wide_cpp_liveshot \
    libchromatix_s5k2l7sa05_rcl_wide_cpp_liveshot_1080 \
    libchromatix_s5k2l7sa05_rcl_wide_cpp_liveshot_4k \
    libchromatix_s5k2l7sa05_rcl_wide_cpp_liveshot_720 \
    libchromatix_s5k2l7sa05_rcl_wide_cpp_preview \
    libchromatix_s5k2l7sa05_rcl_wide_cpp_preview_1080 \
    libchromatix_s5k2l7sa05_rcl_wide_cpp_preview_4k \
    libchromatix_s5k2l7sa05_rcl_wide_cpp_preview_720 \
    libchromatix_s5k2l7sa05_rcl_wide_cpp_snapshot \
    libchromatix_s5k2l7sa05_rcl_wide_cpp_snapshot_1080 \
    libchromatix_s5k2l7sa05_rcl_wide_cpp_snapshot_1080_hdr \
    libchromatix_s5k2l7sa05_rcl_wide_cpp_snapshot_4k \
    libchromatix_s5k2l7sa05_rcl_wide_cpp_snapshot_4k_hdr \
    libchromatix_s5k2l7sa05_rcl_wide_cpp_snapshot_720 \
    libchromatix_s5k2l7sa05_rcl_wide_cpp_snapshot_720_hdr \
    libchromatix_s5k2l7sa05_rcl_wide_cpp_snapshot_hdr \
    libchromatix_s5k2l7sa05_rcl_wide_cpp_video \
    libchromatix_s5k2l7sa05_rcl_wide_cpp_video_1080 \
    libchromatix_s5k2l7sa05_rcl_wide_cpp_video_4k \
    libchromatix_s5k2l7sa05_rcl_wide_cpp_video_720 \
    libchromatix_s5k2l7sa05_rcl_wide_default_preview_3a \
    libchromatix_s5k2l7sa05_rcl_wide_default_video_3a \
    libchromatix_s5k2l7sa05_rcl_wide_hfr_120 \
    libchromatix_s5k2l7sa05_rcl_wide_hfr_120_3a \
    libchromatix_s5k2l7sa05_rcl_wide_hfr_240 \
    libchromatix_s5k2l7sa05_rcl_wide_hfr_240_3a \
    libchromatix_s5k2l7sa05_rcl_wide_hfr_60 \
    libchromatix_s5k2l7sa05_rcl_wide_hfr_60_3a \
    libchromatix_s5k2l7sa05_rcl_wide_postproc \
    libchromatix_s5k2l7sa05_rcl_wide_preview \
    libchromatix_s5k2l7sa05_rcl_wide_preview_1080 \
    libchromatix_s5k2l7sa05_rcl_wide_preview_4k \
    libchromatix_s5k2l7sa05_rcl_wide_preview_720 \
    libchromatix_s5k2l7sa05_rcl_wide_snapshot \
    libchromatix_s5k2l7sa05_rcl_wide_snapshot_1080 \
    libchromatix_s5k2l7sa05_rcl_wide_snapshot_4k \
    libchromatix_s5k2l7sa05_rcl_wide_snapshot_720 \
    libchromatix_s5k2l7sa05_rcl_wide_versions \
    libchromatix_s5k2l7sa05_rcl_wide_video \
    libchromatix_s5k2l7sa05_rcl_wide_video_1080 \
    libchromatix_s5k2l7sa05_rcl_wide_video_4k \
    libchromatix_s5k2l7sa05_rcl_wide_video_720 \
    libchromatix_s5k2l7sa05_rcl_wide_zsl_preview_3a \
    libchromatix_s5k2l7sa05_rcl_wide_zsl_video_3a \
    libchromatix_s5k3h7_rcl_front_4k_preview_3a \
    libchromatix_s5k3h7_rcl_front_4k_video_3a \
    libchromatix_s5k3h7_rcl_front_common \
    libchromatix_s5k3h7_rcl_front_cpp_hfr_120 \
    libchromatix_s5k3h7_rcl_front_cpp_hfr_120_hdr \
    libchromatix_s5k3h7_rcl_front_cpp_hfr_60 \
    libchromatix_s5k3h7_rcl_front_cpp_hfr_60_hdr \
    libchromatix_s5k3h7_rcl_front_cpp_hfr_90 \
    libchromatix_s5k3h7_rcl_front_cpp_hfr_90_hdr \
    libchromatix_s5k3h7_rcl_front_cpp_liveshot \
    libchromatix_s5k3h7_rcl_front_cpp_liveshot_hdr \
    libchromatix_s5k3h7_rcl_front_cpp_preview \
    libchromatix_s5k3h7_rcl_front_cpp_preview_hdr \
    libchromatix_s5k3h7_rcl_front_cpp_snapshot \
    libchromatix_s5k3h7_rcl_front_cpp_snapshot_hdr \
    libchromatix_s5k3h7_rcl_front_cpp_video \
    libchromatix_s5k3h7_rcl_front_cpp_video_4k \
    libchromatix_s5k3h7_rcl_front_cpp_video_4k_hdr \
    libchromatix_s5k3h7_rcl_front_cpp_video_hdr \
    libchromatix_s5k3h7_rcl_front_default_preview_3a \
    libchromatix_s5k3h7_rcl_front_default_video \
    libchromatix_s5k3h7_rcl_front_default_video_3a \
    libchromatix_s5k3h7_rcl_front_hfr_120 \
    libchromatix_s5k3h7_rcl_front_hfr_120_3a \
    libchromatix_s5k3h7_rcl_front_hfr_60 \
    libchromatix_s5k3h7_rcl_front_hfr_60_3a \
    libchromatix_s5k3h7_rcl_front_hfr_90 \
    libchromatix_s5k3h7_rcl_front_hfr_90_3a \
    libchromatix_s5k3h7_rcl_front_liveshot \
    libchromatix_s5k3h7_rcl_front_postproc \
    libchromatix_s5k3h7_rcl_front_preview \
    libchromatix_s5k3h7_rcl_front_snapshot \
    libchromatix_s5k3h7_rcl_front_snapshot_hdr \
    libchromatix_s5k3h7_rcl_front_versions \
    libchromatix_s5k3h7_rcl_front_video_4k \
    libchromatix_s5k3h7_rcl_front_zsl_preview_3a \
    libchromatix_s5k3h7_rcl_front_zsl_video_3a \
    libchromatix_s5k3m3sm_rcl_tele_4k_preview_3a \
    libchromatix_s5k3m3sm_rcl_tele_4k_video_3a \
    libchromatix_s5k3m3sm_rcl_tele_common \
    libchromatix_s5k3m3sm_rcl_tele_cpp_hfr_120 \
    libchromatix_s5k3m3sm_rcl_tele_cpp_hfr_120_hdr \
    libchromatix_s5k3m3sm_rcl_tele_cpp_hfr_60 \
    libchromatix_s5k3m3sm_rcl_tele_cpp_hfr_60_hdr \
    libchromatix_s5k3m3sm_rcl_tele_cpp_liveshot \
    libchromatix_s5k3m3sm_rcl_tele_cpp_preview \
    libchromatix_s5k3m3sm_rcl_tele_cpp_snapshot \
    libchromatix_s5k3m3sm_rcl_tele_cpp_snapshot_hdr \
    libchromatix_s5k3m3sm_rcl_tele_cpp_video \
    libchromatix_s5k3m3sm_rcl_tele_cpp_video_4k \
    libchromatix_s5k3m3sm_rcl_tele_default_preview_3a \
    libchromatix_s5k3m3sm_rcl_tele_default_video_3a \
    libchromatix_s5k3m3sm_rcl_tele_hfr_120 \
    libchromatix_s5k3m3sm_rcl_tele_hfr_120_3a \
    libchromatix_s5k3m3sm_rcl_tele_hfr_60 \
    libchromatix_s5k3m3sm_rcl_tele_hfr_60_3a \
    libchromatix_s5k3m3sm_rcl_tele_liveshot \
    libchromatix_s5k3m3sm_rcl_tele_postproc \
    libchromatix_s5k3m3sm_rcl_tele_preview \
    libchromatix_s5k3m3sm_rcl_tele_snapshot \
    libchromatix_s5k3m3sm_rcl_tele_versions \
    libchromatix_s5k3m3sm_rcl_tele_video \
    libchromatix_s5k3m3sm_rcl_tele_video_4k \
    libchromatix_s5k3m3sm_rcl_tele_zsl_preview_3a \
    libchromatix_s5k3m3sm_rcl_tele_zsl_video_3a \
    libdczoom \
    libdepthmapwrapper \
    libdualcameraddm \
    libfastcvadsp_stub \
    libfastcvopt \
    libflash_lm3646 \
    libfusionLibrary \
    libhal_dbg \
    libjpegdhw \
    libjpegdmahw \
    libjpegehw \
    libmm-qcamera \
    libmmcamera2_c2d_module \
    libmmcamera2_cpp_module \
    libmmcamera2_frame_algorithm \
    libmmcamera2_iface_modules \
    libmmcamera2_imglib_modules \
    libmmcamera2_is \
    libmmcamera2_isp_modules \
    libmmcamera2_mct \
    libmmcamera2_mct_shimlayer \
    libmmcamera2_pp_buf_mgr \
    libmmcamera2_pproc_modules \
    libmmcamera2_q3a_core \
    libmmcamera2_sensor_modules \
    libmmcamera2_stats_algorithm \
    libmmcamera2_stats_lib \
    libmmcamera2_stats_modules \
    libmmcamera_chicony_s5k3h7_rcl_front_eeprom \
    libmmcamera_csidtg \
    libmmcamera_dbg \
    libmmcamera_depth_map \
    libmmcamera_dummyalgo \
    libmmcamera_eebinparse \
    libmmcamera_eeprom_util \
    libmmcamera_eztune_module \
    libmmcamera_facedetection_lib \
    libmmcamera_faceproc \
    libmmcamera_faceproc2 \
    libmmcamera_hdr_gb_lib \
    libmmcamera_hvx_add_constant \
    libmmcamera_hvx_grid_sum \
    libmmcamera_imglib \
    libmmcamera_imglib_faceproc_adspstub \
    libmmcamera_interface \
    libmmcamera_isp_abf48 \
    libmmcamera_isp_aec_bg_stats47 \
    libmmcamera_isp_bf_stats47 \
    libmmcamera_isp_bg_stats46 \
    libmmcamera_isp_bhist_stats44 \
    libmmcamera_isp_black_level48 \
    libmmcamera_isp_bpc48 \
    libmmcamera_isp_cac47 \
    libmmcamera_isp_chroma_enhan40 \
    libmmcamera_isp_chroma_suppress40 \
    libmmcamera_isp_clamp_encoder40 \
    libmmcamera_isp_clamp_video40 \
    libmmcamera_isp_clamp_viewfinder40 \
    libmmcamera_isp_color_correct46 \
    libmmcamera_isp_color_xform_encoder46 \
    libmmcamera_isp_color_xform_video46 \
    libmmcamera_isp_color_xform_viewfinder46 \
    libmmcamera_isp_cs_stats46 \
    libmmcamera_isp_demosaic48 \
    libmmcamera_isp_demux48 \
    libmmcamera_isp_fovcrop_encoder46 \
    libmmcamera_isp_fovcrop_video46 \
    libmmcamera_isp_fovcrop_viewfinder46 \
    libmmcamera_isp_gamma44 \
    libmmcamera_isp_gic48 \
    libmmcamera_isp_gtm46 \
    libmmcamera_isp_hdr48 \
    libmmcamera_isp_hdr_be_stats46 \
    libmmcamera_isp_hdr_bhist_stats44 \
    libmmcamera_isp_ihist_stats46 \
    libmmcamera_isp_linearization40 \
    libmmcamera_isp_ltm47 \
    libmmcamera_isp_luma_adaptation40 \
    libmmcamera_isp_mce40 \
    libmmcamera_isp_mesh_rolloff44 \
    libmmcamera_isp_pdaf48 \
    libmmcamera_isp_pedestal_correct46 \
    libmmcamera_isp_rs_stats46 \
    libmmcamera_isp_scaler_encoder46 \
    libmmcamera_isp_scaler_video46 \
    libmmcamera_isp_scaler_viewfinder46 \
    libmmcamera_isp_sce40 \
    libmmcamera_isp_snr47 \
    libmmcamera_isp_sub_module \
    libmmcamera_m24c64s_rcl_tele_eeprom \
    libmmcamera_m24c64t_rcl_wide_eeprom \
    libmmcamera_paaf_lib \
    libmmcamera_pdaf \
    libmmcamera_pdafcamif \
    libmmcamera_ppbase_module \
    libmmcamera_ppeiscore \
    libmmcamera_quadracfa \
    libmmcamera_rtb_lib \
    libmmcamera_s5k2l7sa05_rcl_wide \
    libmmcamera_s5k3h7_rcl_front \
    libmmcamera_s5k3m3sm_rcl_tele \
    libmmcamera_sat_lib \
    libmmcamera_sw2d_lib \
    libmmcamera_thread_services \
    libmmcamera_tintless_algo \
    libmmcamera_tintless_bg_pca_algo \
    libmmcamera_tuning \
    libmmcamera_tuning_lookup \
    libmmjpeg \
    libmmjpeg_interface \
    libmmlib2d_interface \
    libmmqjpeg_codec \
    libmmqjpegdma \
    libqomx_core \
    libqomx_jpegdec \
    libqomx_jpegenc \
    libqomx_jpegenc_pipe \
    libqtigef \
    libremosaic_daemon \
    libsmwrapper \
    libvpphvx \
    libvpplibrary \
    libvqzip \
    libasphere \
    com.qualcomm.qti.ant@1.0_vendor \
    com.qualcomm.qti.dpm.api@1.0_vendor \
    com.qualcomm.qti.imscmservice@2.0 \
    com.qualcomm.qti.imscmservice@2.1 \
    com.qualcomm.qti.imscmservice@2.2 \
    com.qualcomm.qti.uceservice@2.0 \
    com.qualcomm.qti.uceservice@2.1 \
    com.qualcomm.qti.uceservice@2.2 \
    com.qualcomm.qti.uceservice@2.3 \
    android.hardware.bluetooth@1.0-impl-qti \
    com.qualcomm.qti.ant@1.0-impl \
    fingerprint.msm8998 \
    gatekeeper.msm8998 \
    keystore.msm8998 \
    vendor.qti.hardware.alarm@1.0-impl \
    vulkan.msm8998 \
    lib-imsSDP \
    lib-imscmservice \
    lib-imsdpl \
    lib-imsqimf \
    lib-imsrcs-v2 \
    lib-imsrcsbaseimpl \
    lib-imsvtcore \
    lib-imsxml \
    lib-rcsconfig \
    lib-rtpcommon \
    lib-rtpcore \
    lib-rtpsl \
    lib-siputility \
    lib-uceservice \
    libGPreqcancel \
    libGPreqcancel_svc \
    libQSEEComAPI \
    libadsp_default_listener \
    libcne \
    libcneapiclient \
    libcneoplookup \
    libconfigdb \
    libdataitems \
    libdpmqmihal \
    libdrmfs \
    libdrmtime \
    libdsi_netctrl \
    libflp \
    libgdtap \
    libgeofence \
    libizat_core \
    liblbs_core \
    libloc_api_v02 \
    libloc_ds_api \
    liblqe \
    libnetmgr \
    libnetmgr_common \
    libnetmgr_nr_fusion \
    libnetmgr_rmnet_ext \
    libnlnetmgr \
    libpdmapper \
    libperipheral_client \
    libpn548ad_fw \
    libqcmaputils \
    libqcrilFramework \
    libqcrildatactl \
    libqrtr \
    libqsocket \
    librcc \
    libril-qc-hal-qmi \
    libril-qc-logger \
    libril-qc-ltedirectdisc \
    libril-qc-radioconfig \
    libril-qcril-hook-oem \
    librilqmiservices \
    librpmb \
    libsettings \
    libspl \
    libssd \
    libsystem_health_mon \
    libthermalioctl \
    libtime_genoff \
    libwms \
    libwqe \
    libwvhidl \
    libxml \
    qcrild_librilutils \
    qtibus \
    qtimutex \
    vendor.qti.data.factory@2.0 \
    vendor.qti.data.factory@2.1 \
    vendor.qti.data.factory@2.2 \
    vendor.qti.data.factory@2.3 \
    vendor.qti.data.mwqem@1.0 \
    vendor.qti.data.slm@1.0 \
    vendor.qti.hardware.alarm@1.0 \
    vendor.qti.hardware.data.cne.internal.api@1.0 \
    vendor.qti.hardware.data.cne.internal.constants@1.0 \
    vendor.qti.hardware.data.cne.internal.server@1.0 \
    vendor.qti.hardware.data.connection@1.0 \
    vendor.qti.hardware.data.connection@1.1 \
    vendor.qti.hardware.data.dynamicdds@1.0 \
    vendor.qti.hardware.data.iwlan@1.0 \
    vendor.qti.hardware.data.latency@1.0 \
    vendor.qti.hardware.data.lce@1.0 \
    vendor.qti.hardware.data.qmi@1.0 \
    vendor.qti.hardware.fm@1.0 \
    vendor.qti.hardware.mwqemadapter@1.0 \
    vendor.qti.hardware.radio.am@1.0 \
    vendor.qti.hardware.radio.ims@1.0 \
    vendor.qti.hardware.radio.ims@1.1 \
    vendor.qti.hardware.radio.ims@1.2 \
    vendor.qti.hardware.radio.ims@1.3 \
    vendor.qti.hardware.radio.ims@1.4 \
    vendor.qti.hardware.radio.ims@1.5 \
    vendor.qti.hardware.radio.ims@1.6 \
    vendor.qti.hardware.radio.ims@1.7 \
    vendor.qti.hardware.radio.internal.deviceinfo@1.0 \
    vendor.qti.hardware.radio.lpa@1.0 \
    vendor.qti.hardware.radio.lpa@1.1 \
    vendor.qti.hardware.radio.qcrilhook@1.0 \
    vendor.qti.hardware.radio.qtiradio@1.0 \
    vendor.qti.hardware.radio.qtiradio@2.0 \
    vendor.qti.hardware.radio.qtiradio@2.1 \
    vendor.qti.hardware.radio.qtiradio@2.2 \
    vendor.qti.hardware.radio.qtiradio@2.3 \
    vendor.qti.hardware.radio.qtiradio@2.4 \
    vendor.qti.hardware.radio.uim@1.0 \
    vendor.qti.hardware.radio.uim@1.1 \
    vendor.qti.hardware.radio.uim@1.2 \
    vendor.qti.hardware.radio.uim_remote_client@1.0 \
    vendor.qti.hardware.radio.uim_remote_client@1.1 \
    vendor.qti.hardware.radio.uim_remote_client@1.2 \
    vendor.qti.hardware.radio.uim_remote_server@1.0 \
    vendor.qti.ims.callcapability@1.0 \
    vendor.qti.ims.callinfo@1.0 \
    vendor.qti.ims.factory@1.0 \
    vendor.qti.ims.factory@1.1 \
    vendor.qti.ims.rcsconfig@1.0 \
    vendor.qti.ims.rcsconfig@1.1 \
    vendor.qti.ims.rcsconfig@2.0 \
    vendor.qti.ims.rcsconfig@2.1 \
    vendor.qti.imsrtpservice@3.0-service-Impl \
    vendor.qti.imsrtpservice@3.0_vendor \
    vendor.qti.latency@2.0 \
    vendor.qti.latency@2.1 \
    libadsp_fd_skel \
    libadsp_hvx_add_constant \
    libadsp_hvx_skel \
    libapps_mem_heap \
    libdspCV_skel \
    libfastcvadsp \
    libfastcvadsp_skel \
    libsns_low_lat_stream_skel \
    libvpp_frc \
    libvpp_svc_skel \
    com.qualcomm.qti.ant@1.0 \
    libantradio \
    com.qualcomm.qti.dpm.api@1.0 \
    lib-imscamera \
    lib-imsvideocodec \
    lib-imsvt \
    lib-imsvtextutils \
    lib-imsvtutils \
    libdiag_system \
    libdpmctmgr \
    libdpmfdmgr \
    libdpmframework \
    libdpmtcm \
    libimscamera_jni \
    libimsmedia_jni \
    vendor.qti.diaghal@1.0 \
    vendor.qti.imsrtpservice@3.0 \
    CneApp \
    IWlanService \
    TimeService \
    PowerOffAlarm \
    QtiTelephonyService \
    dpmserviceapp \
    ims \
    qcrilmsgtunnel \
    com.qti.dpmframework \
    dpmapi \
    qcrilhook \
    adpl \
    adsprpcd \
    cnd \
    cnss-daemon \
    dpmQmiMgr \
    hvdcp_opti \
    android.hardware.bluetooth@1.0-service-qti \
    android.hardware.drm@1.1-service.widevine \
    qcrild \
    vendor.qti.hardware.alarm@1.0-service \
    vendor.qti.hardware.perf@1.0-service \
    ims_rtp_daemon \
    imsdatadaemon \
    imsqmidaemon \
    imsrcsd \
    irsc_util \
    loc_launcher \
    lowi-server \
    msm_irqbalance \
    netmgrd \
    pd-mapper \
    pm-proxy \
    pm-service \
    power_off_alarm \
    qrtr-cfg \
    qrtr-lookup \
    qrtr-ns \
    qseecomd \
    qti \
    rmt_storage \
    sensors.qti \
    tftp_server \
    thermal-engine \
    time_daemon \
    xtra-daemon \
    dpmd

PRODUCT_PACKAGES += \
    system_ext_priv-app_ims_lib_arm64_libimscamera_jni_so \
    system_ext_priv-app_ims_lib_arm64_libimsmedia_jni_so \
    vendor_lib_libEGL_adreno_so \
    vendor_lib_libGLESv2_adreno_so \
    vendor_lib_libq3dtools_adreno_so \
    vendor_lib64_libEGL_adreno_so \
    vendor_lib64_libGLESv2_adreno_so \
    vendor_lib64_libq3dtools_adreno_so
